// Generated by gencpp from file turtle_controller/PathResult.msg
// DO NOT EDIT!


#ifndef TURTLE_CONTROLLER_MESSAGE_PATHRESULT_H
#define TURTLE_CONTROLLER_MESSAGE_PATHRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtle_controller
{
template <class ContainerAllocator>
struct PathResult_
{
  typedef PathResult_<ContainerAllocator> Type;

  PathResult_()
    : distanceAccomplished(0.0)  {
    }
  PathResult_(const ContainerAllocator& _alloc)
    : distanceAccomplished(0.0)  {
  (void)_alloc;
    }



   typedef float _distanceAccomplished_type;
  _distanceAccomplished_type distanceAccomplished;




  typedef boost::shared_ptr< ::turtle_controller::PathResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_controller::PathResult_<ContainerAllocator> const> ConstPtr;

}; // struct PathResult_

typedef ::turtle_controller::PathResult_<std::allocator<void> > PathResult;

typedef boost::shared_ptr< ::turtle_controller::PathResult > PathResultPtr;
typedef boost::shared_ptr< ::turtle_controller::PathResult const> PathResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_controller::PathResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_controller::PathResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtle_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'turtle_controller': ['/home/agustin/Agustin/Work/Ekumen/Localwork/ros_turtle/workspace/devel/share/turtle_controller/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtle_controller::PathResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_controller::PathResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_controller::PathResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_controller::PathResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_controller::PathResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_controller::PathResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_controller::PathResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "380abb6f903a91269d728aed7e25e980";
  }

  static const char* value(const ::turtle_controller::PathResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x380abb6f903a9126ULL;
  static const uint64_t static_value2 = 0x9d728aed7e25e980ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_controller::PathResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_controller/PathResult";
  }

  static const char* value(const ::turtle_controller::PathResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_controller::PathResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
float32 distanceAccomplished\n\
";
  }

  static const char* value(const ::turtle_controller::PathResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_controller::PathResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distanceAccomplished);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_controller::PathResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_controller::PathResult_<ContainerAllocator>& v)
  {
    s << indent << "distanceAccomplished: ";
    Printer<float>::stream(s, indent + "  ", v.distanceAccomplished);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_CONTROLLER_MESSAGE_PATHRESULT_H
