// Generated by gencpp from file turtle_controller/PathGoal.msg
// DO NOT EDIT!


#ifndef TURTLE_CONTROLLER_MESSAGE_PATHGOAL_H
#define TURTLE_CONTROLLER_MESSAGE_PATHGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtle_controller
{
template <class ContainerAllocator>
struct PathGoal_
{
  typedef PathGoal_<ContainerAllocator> Type;

  PathGoal_()
    : newPosition()  {
    }
  PathGoal_(const ContainerAllocator& _alloc)
    : newPosition(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _newPosition_type;
  _newPosition_type newPosition;




  typedef boost::shared_ptr< ::turtle_controller::PathGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_controller::PathGoal_<ContainerAllocator> const> ConstPtr;

}; // struct PathGoal_

typedef ::turtle_controller::PathGoal_<std::allocator<void> > PathGoal;

typedef boost::shared_ptr< ::turtle_controller::PathGoal > PathGoalPtr;
typedef boost::shared_ptr< ::turtle_controller::PathGoal const> PathGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_controller::PathGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_controller::PathGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtle_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'turtle_controller': ['/home/agustin/Agustin/Work/Ekumen/Localwork/ros_turtle/workspace/devel/share/turtle_controller/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtle_controller::PathGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_controller::PathGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_controller::PathGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_controller::PathGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_controller::PathGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_controller::PathGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_controller::PathGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d91e5048afafaea7fd02669fd539c788";
  }

  static const char* value(const ::turtle_controller::PathGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd91e5048afafaea7ULL;
  static const uint64_t static_value2 = 0xfd02669fd539c788ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_controller::PathGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_controller/PathGoal";
  }

  static const char* value(const ::turtle_controller::PathGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_controller::PathGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
float32[] newPosition\n\
";
  }

  static const char* value(const ::turtle_controller::PathGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_controller::PathGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.newPosition);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_controller::PathGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_controller::PathGoal_<ContainerAllocator>& v)
  {
    s << indent << "newPosition[]" << std::endl;
    for (size_t i = 0; i < v.newPosition.size(); ++i)
    {
      s << indent << "  newPosition[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.newPosition[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_CONTROLLER_MESSAGE_PATHGOAL_H
