; Auto-generated. Do not edit!


(cl:in-package turtle_controller-msg)


;//! \htmlinclude PathGoal.msg.html

(cl:defclass <PathGoal> (roslisp-msg-protocol:ros-message)
  ((distanceAccomplished
    :reader distanceAccomplished
    :initarg :distanceAccomplished
    :type cl:float
    :initform 0.0))
)

(cl:defclass PathGoal (<PathGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PathGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PathGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name turtle_controller-msg:<PathGoal> is deprecated: use turtle_controller-msg:PathGoal instead.")))

(cl:ensure-generic-function 'distanceAccomplished-val :lambda-list '(m))
(cl:defmethod distanceAccomplished-val ((m <PathGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader turtle_controller-msg:distanceAccomplished-val is deprecated.  Use turtle_controller-msg:distanceAccomplished instead.")
  (distanceAccomplished m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PathGoal>) ostream)
  "Serializes a message object of type '<PathGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'distanceAccomplished))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PathGoal>) istream)
  "Deserializes a message object of type '<PathGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'distanceAccomplished) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PathGoal>)))
  "Returns string type for a message object of type '<PathGoal>"
  "turtle_controller/PathGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PathGoal)))
  "Returns string type for a message object of type 'PathGoal"
  "turtle_controller/PathGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PathGoal>)))
  "Returns md5sum for a message object of type '<PathGoal>"
  "380abb6f903a91269d728aed7e25e980")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PathGoal)))
  "Returns md5sum for a message object of type 'PathGoal"
  "380abb6f903a91269d728aed7e25e980")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PathGoal>)))
  "Returns full string definition for message of type '<PathGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%float32 distanceAccomplished~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PathGoal)))
  "Returns full string definition for message of type 'PathGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%float32 distanceAccomplished~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PathGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PathGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'PathGoal
    (cl:cons ':distanceAccomplished (distanceAccomplished msg))
))
