; Auto-generated. Do not edit!


(cl:in-package turtle_controller-msg)


;//! \htmlinclude PathFeedback.msg.html

(cl:defclass <PathFeedback> (roslisp-msg-protocol:ros-message)
  ((currentDistance
    :reader currentDistance
    :initarg :currentDistance
    :type cl:float
    :initform 0.0))
)

(cl:defclass PathFeedback (<PathFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PathFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PathFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name turtle_controller-msg:<PathFeedback> is deprecated: use turtle_controller-msg:PathFeedback instead.")))

(cl:ensure-generic-function 'currentDistance-val :lambda-list '(m))
(cl:defmethod currentDistance-val ((m <PathFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader turtle_controller-msg:currentDistance-val is deprecated.  Use turtle_controller-msg:currentDistance instead.")
  (currentDistance m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PathFeedback>) ostream)
  "Serializes a message object of type '<PathFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'currentDistance))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PathFeedback>) istream)
  "Deserializes a message object of type '<PathFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'currentDistance) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PathFeedback>)))
  "Returns string type for a message object of type '<PathFeedback>"
  "turtle_controller/PathFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PathFeedback)))
  "Returns string type for a message object of type 'PathFeedback"
  "turtle_controller/PathFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PathFeedback>)))
  "Returns md5sum for a message object of type '<PathFeedback>"
  "32beb4594eb9d6b21b9aa2966d274d31")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PathFeedback)))
  "Returns md5sum for a message object of type 'PathFeedback"
  "32beb4594eb9d6b21b9aa2966d274d31")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PathFeedback>)))
  "Returns full string definition for message of type '<PathFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 currentDistance~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PathFeedback)))
  "Returns full string definition for message of type 'PathFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 currentDistance~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PathFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PathFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PathFeedback
    (cl:cons ':currentDistance (currentDistance msg))
))
