; Auto-generated. Do not edit!


(cl:in-package turtle_controller-msg)


;//! \htmlinclude PathGoal.msg.html

(cl:defclass <PathGoal> (roslisp-msg-protocol:ros-message)
  ((newPosition
    :reader newPosition
    :initarg :newPosition
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass PathGoal (<PathGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PathGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PathGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name turtle_controller-msg:<PathGoal> is deprecated: use turtle_controller-msg:PathGoal instead.")))

(cl:ensure-generic-function 'newPosition-val :lambda-list '(m))
(cl:defmethod newPosition-val ((m <PathGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader turtle_controller-msg:newPosition-val is deprecated.  Use turtle_controller-msg:newPosition instead.")
  (newPosition m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PathGoal>) ostream)
  "Serializes a message object of type '<PathGoal>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'newPosition))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'newPosition))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PathGoal>) istream)
  "Deserializes a message object of type '<PathGoal>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'newPosition) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'newPosition)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PathGoal>)))
  "Returns string type for a message object of type '<PathGoal>"
  "turtle_controller/PathGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PathGoal)))
  "Returns string type for a message object of type 'PathGoal"
  "turtle_controller/PathGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PathGoal>)))
  "Returns md5sum for a message object of type '<PathGoal>"
  "d91e5048afafaea7fd02669fd539c788")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PathGoal)))
  "Returns md5sum for a message object of type 'PathGoal"
  "d91e5048afafaea7fd02669fd539c788")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PathGoal>)))
  "Returns full string definition for message of type '<PathGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%float32[] newPosition~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PathGoal)))
  "Returns full string definition for message of type 'PathGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%float32[] newPosition~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PathGoal>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'newPosition) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PathGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'PathGoal
    (cl:cons ':newPosition (newPosition msg))
))
